public enum Errors {
    NO_VERTEX_FIRST,
    NO_VERTEX_SECOND,
    EMPTY_VERTEX_FIRST,
    EMPTY_VERTEX_SECOND,
    SIMILAR_IN_BOTH,
    SIMILAR_IN_FIRST,
    SIMILAR_IN_SECOND,
    NO_EDGES,
    SIMILAR_EDGES,
    NONE
}
